---
deployment:
  tasks:
    - export DEPLOYPATH=/home/donald52/public_html
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp -R downloads $DEPLOYPATH
